### PR TITLE
Group workshop updates

### PR DESCRIPTION
**Pull request by danomatika**
Howdy, thanks for the repo! We used this for a set of AI writing workshops here at the Center for Art & Media Karlsruhe ([ZKM](https://zkm.de)) during the AI on the Couch event back in November 2023: https://zkm.de/en/event/2023/11/ai-on-the-couch

The workshop was built around groups taking turn writing their own parts between "folding" so I made some changes to how the interaction works as well added command line options to control this. If no options are specified, the original behavior is preserved.

A overview changelog:
* added Makefile and wrapper run script to make venv creation and usage easier
* added command line options
* added "unfold" mode where text stays hidden after folding, this was needed when passing between people so they could not see if ChatGPT had answered before they wrote
* added option to insert writer tags: `<human>` or `<ai>` which can then be revealed after the text is revealed (they are always saved in output file)
* added dummy mode for testing without OpenAI account
* config and instructions can be overridden on command line, this make it easier for using a set of different configurations
* added get text locale support with translations (currently EN and DE)
* added key bindings for most actions
* changed references from "Poem" to "Text" since instructions can be changed to produce free form / non-poetry output (ie. story)
* updated attribution
* various small UI improvements
* a few bugfixes
* probably a few other things I am forgetting after a couple months, skim the README and git history

For reference on the options and some of the new functionality added, here is the current `-h/--help` output:
~~~
% ./exquisite -h
usage: exquisite.py [-h] [--config CONFIGFILE] [--fontsize FONTSIZE] [-u] [-r] [--randomai RANDOM_AI] [-d] [-b] [-t] [--maxwords MAX_WORDS] [-s SLEEP] [-v] [INSTRUCT]

Exquisite Corpse, according to ChatGPT

positional arguments:
  INSTRUCT              custom ChatGPT instructions txt file

options:
  -h, --help            show this help message and exit
  --config CONFIGFILE   custom ChatGPT configuration json file
  --fontsize FONTSIZE   textbox font size in points, default: 12
  -u, --unfold          enable interim "unfolded" state to hide previous input, ie. when used within a group
  -r, --random          randomly choose between ai and human when folding
  --randomai RANDOM_AI  percent chance to get an ai response 0-100, default: 50
  -d, --dummyai         use dummy ai text instead of ChatGPT (saves money when testing)
  -b, --breaks          force line breaks between folds
  -t, --tags            prepend writer tag lines per fold: <ai> or <human>, adds Reveal Writers menu item
  --maxwords MAX_WORDS  max allowed words for prev line, useful for story text which may not use line breaks, default: 0 (allow all)
  -s SLEEP, --sleep SLEEP
                        delay to sleep after a human folds in seconds when --unfold is enabled, default: 0 (none)
  -v, --verbose         enable verbose printing
~~~

### CODE REVIEW

**Comment by danomatika** [comment]
For our usage, we focused on simple story writing in German, so the instructions and config were modified and we used the following options in a run script:

~~~
./exquisite --unfold --random --randomai 15 --breaks --tags --fontsize 16 --maxwords 15 --sleep 4 --config gpt_config.json instructions.txt
~~~

Overall, it worked pretty well and the response from participants was enthusiastic. I could probably add these configs as examples too.

Also, if you want, I can make a changelog.

**Comment by danomatika** [comment]
Here is a demo development video from November showing the fold/unfold behavior and writer tagging: https://zkm.cloud/s/6bm3XTQAxkP5Wpm

**Comment by danomatika** [comment]
Oh, I forgot that we tested this only on macOS. The key bindings and menu accelerators should probably be checked on Windows / Linux.

**Comment by karencfisher** [comment]
Wow! I am amazingly flattered and pleased to see that you used the code for your AI writing workshops! I am really glad that someone has made use of (and enhanced) my project. Thank you for all your contributions.

**Comment by karencfisher** [comment]
Would there be recordings of some of the sessions online by chance? It sounds like it was a fascinating program. I wish I could have been there!

**Comment by danomatika** [comment]
> Would there be recordings of some of the sessions online by chance? It sounds like it was a fascinating program. I wish I could have been there!

There are some photos but they are not organized yet. I can get back to you if/when they are available.

**Pull request merged**
